# Generated by Django 4.0.3 on 2022-05-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0102_alter_vehiculo_clase_alter_vehiculo_configuracion'),
        ('dashboards', '0109_inspeccion_eje'),
    ]

    operations = [
    ]
