# Django
from django.urls import path
from django.views.generic.base import View

# Views
from dashboards import views

urlpatterns = [
    path(
        route="",
        view=views.HomeView.as_view(),
        name="home"
    ),
    path(
        route="pulpo/",
        view=views.PulpoView.as_view(),
        name="pulpo"
    ),
    path(
        route="api/",
        view=views.VehiculoAPI.as_view(),
        name="api"
    ),
    path(
        route="api/pro/",
        view=views.PulpoProAPI.as_view(),
        name="apiPro"
    ),
    path(
        route="buscar/",
        view=views.buscar,
        name="buscar"
    ),
    path(
        route="config/",
        view=views.ConfigView.as_view(),
        name="config"
    ),
    path(
        route="search/",
        view=views.SearchView.as_view(),
        name="search"
    ),
    path(
        route="search_id/",
        view=views.search,
        name="search_id"
    ),
    path(
        route="<int:pk>/",
        view=views.DetailView.as_view(),
        name="detail"
    ),
    path(
        route="estatusDeFlota",
        view=views.TireDBView.as_view(),
        name="tireDB1"
    ),
    path(
        route="reemplazoEstimado",
        view=views.TireDB2View.as_view(),
        name="tireDB2"
    ),
    path(
        route="rendimientoDeLlanta",
        view=views.TireDB3View.as_view(),
        name="tireDB3"
    ),
    path(
        route="login/",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="logout/",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="hub",
        view=views.hubView.as_view(),
        name="hub"
    ),
    path(
        route="reporte",
        view=views.ParametroExtractoView.as_view(),
        name="ParametroExtracto"
    ),
    path(
        route="dashboards",
        view=views.SiteMenuView.as_view(),
        name="siteMenu"
    ),
    path(
        route="desechos",
        view=views.catalogoDesechosView.as_view(),
        name="catalogoDesechos"
    ),
    path(
        route="productos",
        view=views.catalogoProductoView.as_view(),
        name="catalogoProductos"
    ),
    path(
        route="renovadores",
        view=views.catalogoRenovadoresView.as_view(),
        name="catalogoRenovadores"
    ),
    path(
        route="4umbrales",
        view=views.CuatroUmbralesView.as_view(),
        name="CuatroUmbrales"
    ),
    path(
        route="serialVehiculo",
        view=views.SerialVehiculoView.as_view(),
        name="SerialVehiculo"
    ),
    path(
        route="tireEyeView",
        view=views.TireEyeView.as_view(),
        name="TireEyeView"
    ),
    path(
        route="tireDetail/<int:pk>/",
        view=views.tireDetailView.as_view(),
        name="tireDetail"
    ),
    path(
        route="diagrama",
        view=views.diagramaView.as_view(),
        name="diagrama"
    ),
    path(
        route="tireDiagrama",
        view=views.tireDiagramaView.as_view(),
        name="tireDiagrama"
    ),
    path(
        route="reporteVehiculo/<int:pk>/",
        view=views.reporteVehiculoView.as_view(),
        name="reporteVehiculo"
    ),
    path(
        route="reporteLlanta",
        view=views.reporteLlantaView.as_view(),
        name="reporteLlanta"
    ),
    path(
        route="configuracionVehiculo",
        view=views.configuracionVehiculoView.as_view(),
        name="configuracionVehiculo"
    ),
    path(
        route="configuracionLlanta",
        view=views.configuracionLlantaView.as_view(),
        name="configuracionLlanta"
    ),
    path(
        route="almacen",
        view=views.almacenView.as_view(),
        name="almacen"
    ),
    path(
        route="antesDesechar",
        view=views.antesDesecharView.as_view(),
        name="antesDesechar"
    ),
    path(
        route="antesRenovar",
        view=views.antesRenovarView.as_view(),
        name="antesRenovar"
    ),
    path(
        route="conRenovador",
        view=views.conRenovadorView.as_view(),
        name="conRenovador"
    ),
    path(
        route="desechoFinal",
        view=views.desechoFinalView.as_view(),
        name="desechoFinal"
    ),
    path(
        route="nueva",
        view=views.nuevaView.as_view(),
        name="nueva"
    ),
    path(
        route="renovada",
        view=views.renovadaView.as_view(),
        name="renovada"
    ),
    path(
        route="servicio",
        view=views.servicioView.as_view(),
        name="servicio"
    ),
    path(
        route="rodante",
        view=views.rodanteView.as_view(),
        name="rodante"
    ),
    path(
        route="procesoDesecho",
        view=views.procesoDesechoView.as_view(),
        name="procesoDesecho"
    ),
    path(
        route="ordenSalidaRen",
        view=views.ordenSalidaRenView.as_view(),
        name="ordenSalidaRen"
    ),
    path(
        route="ordenEntrada",
        view=views.ordenEntradaView.as_view(),
        name="ordenEntrada"
    ),
    path(
        route="ordenLlanta",
        view=views.ordenLlantaView.as_view(),
        name="ordenLlanta"
    ),
    path(
        route="tallerDestino",
        view=views.tallerDestinoView.as_view(),
        name="tallerDestino"
    ),
    path(
        route="stockDestino",
        view=views.stockDestinoView.as_view(),
        name="stockDestino"
    ),
    path(
        route="procesoRenovado",
        view=views.procesoRenovadoView.as_view(),
        name="procesoRenovado"
    ),
    path(
        route="planTrabajo",
        view=views.planTrabajoView.as_view(),
        name="planTrabajo"
    ),
    path(
        route="calendario",
        view=views.calendarView.as_view(),
        name="calendario"
    ),
]